#!/bin/bash 

set -e

PACKAGES="ruby ruby-faraday"
for PACKAGE in $PACKAGES; do
    if ! dpkg -l $PACKAGE 2>/dev/null|grep -q "^ii"; then
        apt-get update && apt-get -y install $PACKAGES
        break
    fi
done

if ! gem list|grep -q "^money "; then
    gem install money
fi
