// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1579107678);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1579107798);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1579150976);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1578984414);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1579107919);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("extensions.blocklist.lastModified", "Tue, 14 Jan 2020 22:08:07 GMT");
user_pref("extensions.blocklist.pingCountTotal", 7);
user_pref("extensions.blocklist.pingCountVersion", 7);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1579107679);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190520110519");
user_pref("extensions.lastAppVersion", "60.7.0");
user_pref("extensions.lastPlatformVersion", "60.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("idle.lastDailyNotification", 1579129557);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "532fd8b5-ead7-4010-a085-4483d32a3da");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "60.7.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1579129558);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("services.blocklist.addons.checked", 1579107790);
user_pref("services.blocklist.clock_skew_seconds", 8);
user_pref("services.blocklist.gfx.checked", 1579107790);
user_pref("services.blocklist.last_etag", "\"1579101106042\"");
user_pref("services.blocklist.last_update_seconds", 1579107790);
user_pref("services.blocklist.onecrl.checked", 1579107790);
user_pref("services.blocklist.pinning.checked", 1579107790);
user_pref("services.blocklist.plugins.checked", 1579107790);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1578610615);
user_pref("toolkit.telemetry.cachedClientID", "f327b853-8d83-4767-8048-0a54ed5401ef");
user_pref("toolkit.telemetry.previousBuildID", "20190520110519");
user_pref("toolkit.telemetry.prompted", 2);
